version: '3.7'

services:
    database:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      ports:
        - '3306'

    phpmyadmin:
      image: phpmyadmin
      container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
      restart: always
      depends_on:
        - database
      ports:
        - 8080:80
      environment:
        PMA_HOST: database